name: CI
on: [push]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install # will run `yarn install` command
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build # will run `yarn build` command
      - uses: wei/curl@master
        with:
          curl: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip
          curl: unzip awscliv2.zip
          curl: sudo ./aws/install
          curl: aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY }}
          curl: aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_KEY }}
          curl: aws configure set default.region us-east-1
          curl: aws s3 sync --delete ./dist s3://swinghelperdevelopment


          # args: aws cloudfront create-invalidation --distribution-id E247WE6NQC2UAJ --paths "/*"
